(eval-when-compile    (require 'color-theme))
(defun color-theme-tango-dark2 ()
  "Color theme by mikerose, created 2014-11-08."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#2e3436")
      (background-mode . dark)
      (border-color . "#888a85")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "#8ae234"))
     ((list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#2e3436" :foreground "#eeeeec" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "outline" :family "Courier New"))))
     (\` ((t (nil))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "#888a85"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "#729fcf"))))
     (comint-highlight-input ((t (:italic t :bold t :slant italic :weight bold))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "Courier New" :foundry "outline" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#eeeeec" :background "#2e3436" :stipple nil :height 98))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "#fce94f"))))
     (ediff-current-diff-A ((t (:background "#555753"))))
     (ediff-current-diff-B ((t (:background "#555753"))))
     (ediff-even-diff-A ((t (:background "#41423f"))))
     (ediff-even-diff-B ((t (:background "#41423f"))))
     (ediff-fine-diff-A ((t (:background "#204a87"))))
     (ediff-fine-diff-B ((t (:background "#8f5902"))))
     (ediff-odd-diff-A ((t (:background "#41423f"))))
     (ediff-odd-diff-B ((t (:background "#41423f"))))
     (error ((t (:bold t :foreground "#ff4b4b" :weight bold))))
     (escape-glyph ((t (:foreground "#c4a000"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flyspell-duplicate ((t (:underline "#fcaf3e"))))
     (flyspell-incorrect ((t (:underline (\, red-1)))))
     (font-lock-builtin-face ((t (:foreground "#ad7fa8"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#73d216"))))
     (font-lock-comment-face ((t (:foreground "#73d216"))))
     (font-lock-constant-face ((t (:foreground "#e6a8df"))))
     (font-lock-doc-face ((t (:foreground "#888a85"))))
     (font-lock-function-name-face ((t (:italic t :bold t :foreground "#fce94f" :slant italic :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "#b4fa70" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "#ad7fa8"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:italic t :foreground "#e9b96e" :slant italic))))
     (font-lock-type-face ((t (:bold t :foreground "#8cc4ff" :weight bold))))
     (font-lock-variable-name-face ((t (:foreground "#fcaf3e"))))
     (font-lock-warning-face ((t (:bold t :foreground "#ff4b4b" :weight bold))))
     (fringe ((t (:background "#2e3436"))))
     (glyphless-char ((t (:height 0.6))))
     (gnus-group-mail-1 ((t (:foreground "#ad7fa8"))))
     (gnus-group-mail-1-low ((t (:foreground "#75507b"))))
     (gnus-group-mail-2 ((t (:foreground "#729fcf"))))
     (gnus-group-mail-2-low ((t (:foreground "#3465a4"))))
     (gnus-group-mail-3 ((t (:foreground "#8ae234"))))
     (gnus-group-mail-3-low ((t (:foreground "#73d216"))))
     (gnus-group-mail-low ((t (:foreground "#edd400"))))
     (gnus-group-news-1 ((t (:foreground "#ad7fa8"))))
     (gnus-group-news-1-low ((t (:foreground "#75507b"))))
     (gnus-group-news-2 ((t (:foreground "#729fcf"))))
     (gnus-group-news-2-low ((t (:foreground "#3465a4"))))
     (gnus-group-news-3 ((t (:foreground "#8ae234"))))
     (gnus-group-news-3-low ((t (:foreground "#73d216"))))
     (gnus-group-news-4 ((t (:foreground "#e6a8df"))))
     (gnus-group-news-4-low ((t (:foreground "#c17d11"))))
     (gnus-group-news-5 ((t (:foreground "#fcaf3e"))))
     (gnus-group-news-5-low ((t (:foreground "#f57900"))))
     (gnus-group-news-low ((t (:foreground "#edd400"))))
     (gnus-header-content ((t (:foreground "#c4a000" :weight normal))))
     (gnus-header-from ((t (:foreground "#edd400"))))
     (gnus-header-name ((t (:foreground "#729fcf"))))
     (gnus-header-newsgroups ((t (:foreground "#c17d11"))))
     (gnus-header-subject ((t (:foreground "#8ae234"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "#edd400" :foreground "#2e3436"))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     (isearch ((t (:background "#ce5c00" :foreground "#eeeeec"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "#8f5902" :foreground "#eeeeec"))))
     (link ((t (:foreground "#729fcf" :underline t))))
     (link-visited ((t (:foreground "#3465a4" :underline t))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
     (message-cited-text ((t (:foreground "#8ae234"))))
     (message-header-cc ((t (:foreground "#c4a000"))))
     (message-header-name ((t (:foreground "#729fcf"))))
     (message-header-other ((t (:foreground "#c17d11"))))
     (message-header-subject ((t (:foreground "#8ae234"))))
     (message-header-to ((t (:foreground "#edd400"))))
     (message-separator ((t (:foreground "#ad7fa8"))))
     (minibuffer-prompt ((t (:bold t :foreground "#729fcf" :weight bold))))
     (mode-line ((t (:background "#d3d7cf" :foreground "#2e3436" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#555753" :foreground "#bbbbbc" :box (:line-width -1 :style released-button) :weight light))))
     (mouse ((t (nil))))
     (next-error ((t (:background "#555753"))))
     (nobreak-space ((t (:foreground "#c4a000" :underline t))))
     (query-replace ((t (:foreground "#eeeeec" :background "#ce5c00"))))
     (region ((t (:background "#555753"))))
     (scroll-bar ((t (:foreground "systemscrollbar"))))
     (secondary-selection ((t (:background "#204a87"))))
     (semantic-decoration-on-includes ((t (:underline "#888a85"))))
     (semantic-decoration-on-private-members-face ((t (:background "#5c3566"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#8f5902"))))
     (semantic-decoration-on-unknown-includes ((t (:background "#a40000"))))
     (semantic-decoration-on-unparsed-includes ((t (:background "#41423f"))))
     (semantic-tag-boundary-face ((t (:overline "#729fcf"))))
     (semantic-unmatched-syntax-face ((t (:underline "#ef2929"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match-face ((t (:background "#73d216" :foreground "#2e3436"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (smerge-refined-change ((t (:background "#204a87"))))
     (success ((t (:bold t :foreground "#8ae234" :weight bold))))
     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "systeminfowindow" :foreground "systeminfotext"))))
     (trailing-whitespace ((t (:background "#a40000"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "#fcaf3e" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray")))))))
(add-to-list 'color-themes '(my-color-theme  "Tango Dark" "Michael Rose"))
