# --- General behavior ---
set -g default-terminal "screen-256color"
set-option -g history-limit 50000
set -g display-time 2000
# Create new windows using the home directory
bind c new-window -c "$HOME"
# fix ssh agent when tmux is detached
set-option -g update-environment -r

# --- Prefix & config reload ---
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Reload config with Prefix + r
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# --- Keybindings ---
# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# --- STYLES & Status bar ---
# Make the status bar more visible
# set -g status-bg red
# set -g status-fg white

# Highlight active window
# set-window-option -g window-status-current-style bg=brightblue,fg=black,bold
# set-window-option -g window-status-format " #I: #W "
# set-window-option -g window-status-current-format " #I: #W#F "

# Dim inactive windows
# set-window-option -g window-status-style fg=gray

# Make active pane border obvious
# set-option -g pane-active-border-style fg=brightblue
# set-option -g pane-border-style fg=gray


# Source theme here!
source-file ~/repos/computer_setup/my-awesome-theme.tmux.conf


# Enable mouse control (clickable windows, panes, resizable panes)
# set -g mouse on

# don't rename windows automatically
# set-option -g allow-rename off
