# set -g default-terminal "screen-256color"

# fix ssh agent when tmux is detached
set-option -g update-environment -r
# setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf


set-option -g history-limit 50000

set -g status-bg red

# Create new windows using the home directory
bind c new-window -c "$HOME"

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
# set -g mouse on

# don't rename windows automatically
# set-option -g allow-rename off
