name: base
channels:
  - conda-forge
dependencies:
  - ipython
  - jupyter
  - numpy
  - pandas
  - plotly
  - polars
  - scikit-learn
  - scipy
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio



